var annotated =
[
    [ "irr", "namespaceirr.html", "namespaceirr" ],
    [ "AI", "class_a_i.html", "class_a_i" ],
    [ "AmmoShell", "class_ammo_shell.html", "class_ammo_shell" ],
    [ "Ammunition", "class_ammunition.html", "class_ammunition" ],
    [ "CombatUnit", "class_combat_unit.html", "class_combat_unit" ],
    [ "ConstructionPlant", "class_construction_plant.html", "class_construction_plant" ],
    [ "Division", "class_division.html", "class_division" ],
    [ "ElectricPower", "class_electric_power.html", "class_electric_power" ],
    [ "ExtractingUnit", "class_extracting_unit.html", "class_extracting_unit" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "Harvester", "class_harvester.html", "class_harvester" ],
    [ "LayerLandscape", "class_layer_landscape.html", "class_layer_landscape" ],
    [ "LayerSpice", "class_layer_spice.html", "class_layer_spice" ],
    [ "MachinePlant", "class_machine_plant.html", "class_machine_plant" ],
    [ "Map", "class_map.html", "class_map" ],
    [ "MapLandscape", "class_map_landscape.html", "class_map_landscape" ],
    [ "MapSpice", "class_map_spice.html", "class_map_spice" ],
    [ "MyReceiver", "class_my_receiver.html", "class_my_receiver" ],
    [ "Object", "class_object.html", "class_object" ],
    [ "ObjectWithModel", "class_object_with_model.html", "class_object_with_model" ],
    [ "Price", "class_price.html", "class_price" ],
    [ "Resource", "class_resource.html", "class_resource" ],
    [ "RTSCamera", "class_r_t_s_camera.html", "class_r_t_s_camera" ],
    [ "Silo", "class_silo.html", "class_silo" ],
    [ "Spice", "class_spice.html", "class_spice" ],
    [ "SpicePlant", "class_spice_plant.html", "class_spice_plant" ],
    [ "State", "class_state.html", "class_state" ],
    [ "Structure", "class_structure.html", "class_structure" ],
    [ "Tank", "class_tank.html", "class_tank" ],
    [ "Team", "class_team.html", "class_team" ],
    [ "Unit", "class_unit.html", "class_unit" ],
    [ "WindTurbine", "class_wind_turbine.html", "class_wind_turbine" ]
];