/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main_frame;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultRowSorter;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import main_compare.DateCompare;
import main_сlasses.MusicalRecording;
import main_сlasses.SongInformation;

/**
 *
 * @author константин
 */
public class JDialogPopularMusic extends javax.swing.JDialog {

/**
 * Creates new form JDialogPopularMusic
 */
public JDialogPopularMusic(java.awt.Frame parent, boolean modal,ArrayList<MusicalRecording> music) {
    super(parent, modal);
    initComponents();
    this.music=music;
 this.getContentPane().setBackground(Color.white);
    this.initializeFields();
    this.changingComponents();
}
private void initializeFields()
{
   picture=Toolkit.getDefaultToolkit().getImage("program/155.jpg");
   this.pictureLabel=new ImageIcon("program/13.png");
   this.jLabelQuestion.setIcon(this.pictureLabel);
   this.jPopupMenu1=new JPopupMenu();
}
private void changingComponents()
{
    DefaultTableCellRenderer r = (DefaultTableCellRenderer) this.jTableMusic.getDefaultRenderer(String.class);
    r.setHorizontalAlignment(JLabel.CENTER);
    r.setVerticalAlignment(JLabel.CENTER);
    r = (DefaultTableCellRenderer) this.jTableMusic.getTableHeader().getDefaultRenderer();
    r.setHorizontalAlignment(JLabel.CENTER);
    r.setVerticalAlignment(JLabel.CENTER);
    this.jTableMusic.getColumnModel().getColumn(0).setMinWidth(340);
    this.jTableMusic.getColumnModel().getColumn(0).setMaxWidth(340);
    DefaultRowSorter a= (DefaultRowSorter) this.jTableMusic.getRowSorter();
        a.setComparator(2,new DateCompare());
}
/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMusic = new javax.swing.JTable();
        jButtonExit = new javax.swing.JButton();
        jLabelPoupMenu = new javax.swing.JLabel();
        jLabelQuestion = new javax.swing.JLabel();
        jLabelListPopularMusic = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("main_frame/Bundle"); // NOI18N
        setTitle(bundle.getString("JDialogPopularMusic.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setModal(true);
        setResizable(false);
        addWindowListener(formListener);
        getContentPane().setLayout(null);

        jTableMusic.setAutoCreateRowSorter(true);
        jTableMusic.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        jTableMusic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Название", "Жанр", "Дата создания"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMusic.setFillsViewportHeight(true);
        jTableMusic.setGridColor(new java.awt.Color(51, 51, 51));
        jTableMusic.setRequestFocusEnabled(false);
        jTableMusic.setRowHeight(20);
        jTableMusic.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableMusic.getTableHeader().setResizingAllowed(false);
        jTableMusic.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableMusic);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 70, 700, 370);

        jButtonExit.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonExit.setText(bundle.getString("JDialogPopularMusic.jButtonExit.text")); // NOI18N
        jButtonExit.setToolTipText(bundle.getString("JDialogPopularMusic.jButtonExit.toolTipText")); // NOI18N
        jButtonExit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jButtonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonExit.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonExit.setFocusable(false);
        jButtonExit.setName("exit"); // NOI18N
        jButtonExit.setRolloverEnabled(false);
        jButtonExit.addMouseListener(formListener);
        jButtonExit.addActionListener(formListener);
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(330, 590, 320, 60);

        jLabelPoupMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPoupMenu.setText(bundle.getString("JDialogPopularMusic.jLabelPoupMenu.text")); // NOI18N
        getContentPane().add(jLabelPoupMenu);
        jLabelPoupMenu.setBounds(140, 440, 20, 20);

        jLabelQuestion.setIcon(new javax.swing.ImageIcon("C:\\Users\\константин\\Documents\\NetBeansProjects\\13.png")); // NOI18N
        jLabelQuestion.setText(bundle.getString("JDialogPopularMusic.jLabelQuestion.text")); // NOI18N
        jLabelQuestion.addMouseListener(formListener);
        getContentPane().add(jLabelQuestion);
        jLabelQuestion.setBounds(490, 470, 34, 30);

        jLabelListPopularMusic.setBackground(new java.awt.Color(255, 255, 255));
        jLabelListPopularMusic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelListPopularMusic.setText(bundle.getString("JDialogPopularMusic.jLabelListPopularMusic.text")); // NOI18N
        getContentPane().add(jLabelListPopularMusic);
        jLabelListPopularMusic.setBounds(310, 20, 370, 30);

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.WindowListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jButtonExit) {
                JDialogPopularMusic.this.jButtonExitActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jButtonExit) {
                JDialogPopularMusic.this.jButtonExitMouseEntered(evt);
            }
            else if (evt.getSource() == jLabelQuestion) {
                JDialogPopularMusic.this.jLabelQuestionMouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jButtonExit) {
                JDialogPopularMusic.this.jButtonExitMouseExited(evt);
            }
            else if (evt.getSource() == jLabelQuestion) {
                JDialogPopularMusic.this.jLabelQuestionMouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }

        public void windowActivated(java.awt.event.WindowEvent evt) {
        }

        public void windowClosed(java.awt.event.WindowEvent evt) {
        }

        public void windowClosing(java.awt.event.WindowEvent evt) {
        }

        public void windowDeactivated(java.awt.event.WindowEvent evt) {
        }

        public void windowDeiconified(java.awt.event.WindowEvent evt) {
        }

        public void windowIconified(java.awt.event.WindowEvent evt) {
        }

        public void windowOpened(java.awt.event.WindowEvent evt) {
            if (evt.getSource() == JDialogPopularMusic.this) {
                JDialogPopularMusic.this.formWindowOpened(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.fillTable();
        this.repaint();
    }//GEN-LAST:event_formWindowOpened
protected void fillTable()
{
    String[] str=new String[6]; 
    DefaultTableModel table=(DefaultTableModel) this.jTableMusic.getModel();
    for(MusicalRecording v:this.music)
    {
        if(v.getSong().getGenre().equalsIgnoreCase(SongInformation.CLASSIC)==false)
        {
             str[0]=v.getSong().getName();
            str[1]=this.russificationGenre(v.getSong().getGenre());
            if(new DateCompare().compare(v.getSong().getCreationDate(), "1.1.1")!=0)
                str[2]=v.getSong().getCreationDate();
            else
                str[2]=" ";
            table.addRow(str);
        }
    }
}
protected String russificationGenre(String str)
{
    String s=null;
    if(str.equalsIgnoreCase(SongInformation.CLASSIC))
    {
        s="Классика";
    }
    else
    {
        if(str.equalsIgnoreCase(SongInformation.JAZZ))
        {
            s="Джаз";
        }
        else
        {
            if(str.equalsIgnoreCase(SongInformation.POP))
            {
                s="Поп";
            }
            else
                s="Рок";
        }
    }
    return s;
}
    private void jButtonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMouseEntered
        // TODO add your handling code here:
        jButtonExit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
    }//GEN-LAST:event_jButtonExitMouseEntered

    private void jButtonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMouseExited
        // TODO add your handling code here:
        jButtonExit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jButtonExitMouseExited

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jLabelQuestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuestionMouseEntered
        // TODO add your handling code here:
        this.jPopupMenu1.removeAll();
        this.jPopupMenu1.add("Для сортировки по определенному полю нажмите заголовок соответствующего столбца.");
        this.jPopupMenu1.show(this.jLabelPoupMenu,0, 0);
    }//GEN-LAST:event_jLabelQuestionMouseEntered

    private void jLabelQuestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuestionMouseExited
        // TODO add your handling code here:
        this.jPopupMenu1.setVisible(false);
    }//GEN-LAST:event_jLabelQuestionMouseExited

/**
 * @param args the command line arguments
 */
    @Override
public void paint(Graphics g)
{
    g.drawImage(this.picture, 0, 25, this);
    this.paint_1();
}
@Override
public void update(Graphics g)
{
    g.drawImage(this.picture, 0, 25,this);
    this.update_1();
    
}
public void paint_1()
{
    for(int i=0;i<this.getContentPane().getComponentCount();i++)
    {
        this.getContentPane().getComponent(i).repaint();
    }
}
public void update_1()
{
    for(int i=0;i<this.getContentPane().getComponentCount();i++)
    {
        this.getContentPane().getComponent(i).update(this.getContentPane().getComponent(i).getGraphics());
    }
}
protected ArrayList<MusicalRecording> music;//пременная хранящая объект кторый получен из родительской формы
protected Image picture;//заставка
protected JPopupMenu jPopupMenu1; 
protected ImageIcon pictureLabel;//картинка для надписи
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelListPopularMusic;
    private javax.swing.JLabel jLabelPoupMenu;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMusic;
    // End of variables declaration//GEN-END:variables
}
